"""initial migration

Revision ID: 950ae4d6d476
Revises:
Create Date: 2025-07-27 11:49:06.452066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "950ae4d6d476"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_requirements",
        sa.Column("referral_count_for_free_month", sa.BigInteger(), nullable=False),
        sa.Column("premium_price", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admin_requirements_id"), "admin_requirements", ["id"], unique=False
    )
    op.create_table(
        "backup",
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_backup_id"), "backup", ["id"], unique=False)
    op.create_index(
        op.f("ix_backup_message_id"), "backup", ["message_id"], unique=False
    )
    op.create_index(op.f("ix_backup_url"), "backup", ["url"], unique=False)
    op.create_table(
        "channels",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
        sa.UniqueConstraint("link"),
    )
    op.create_index(op.f("ix_channels_id"), "channels", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("tg_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("language_code", sa.String(length=8), nullable=True),
        sa.Column("is_tg_premium", sa.Boolean(), nullable=False),
        sa.Column("last_active", sa.DateTime(), nullable=False),
        sa.Column("referred_by", sa.BigInteger(), nullable=True),
        sa.Column("subscription_expiry", sa.DateTime(), nullable=True),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("tokens", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("tg_id", "id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_last_name"), "users", ["last_name"], unique=False)
    op.create_index(
        op.f("ix_users_referred_by"), "users", ["referred_by"], unique=False
    )
    op.create_index(
        op.f("ix_users_subscription_expiry"),
        "users",
        ["subscription_expiry"],
        unique=False,
    )
    op.create_index(op.f("ix_users_tg_id"), "users", ["tg_id"], unique=True)
    op.create_index(op.f("ix_users_tokens"), "users", ["tokens"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "referrals",
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("invited_tg_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["tg_id"], ["users.tg_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tg_id", "id"),
    )
    op.create_index(op.f("ix_referrals_id"), "referrals", ["id"], unique=False)
    op.create_table(
        "statistics",
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("from_text", sa.BigInteger(), nullable=False),
        sa.Column("from_voice", sa.BigInteger(), nullable=False),
        sa.Column("from_youtube", sa.BigInteger(), nullable=False),
        sa.Column("from_tiktok", sa.BigInteger(), nullable=False),
        sa.Column("from_like", sa.BigInteger(), nullable=False),
        sa.Column("from_snapchat", sa.BigInteger(), nullable=False),
        sa.Column("from_instagram", sa.BigInteger(), nullable=False),
        sa.Column("from_twitter", sa.BigInteger(), nullable=False),
        sa.Column("from_video", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["tg_id"], ["users.tg_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tg_id", "id"),
    )
    op.create_index(op.f("ix_statistics_id"), "statistics", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_statistics_id"), table_name="statistics")
    op.drop_table("statistics")
    op.drop_index(op.f("ix_referrals_id"), table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_tokens"), table_name="users")
    op.drop_index(op.f("ix_users_tg_id"), table_name="users")
    op.drop_index(op.f("ix_users_subscription_expiry"), table_name="users")
    op.drop_index(op.f("ix_users_referred_by"), table_name="users")
    op.drop_index(op.f("ix_users_last_name"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_channels_id"), table_name="channels")
    op.drop_table("channels")
    op.drop_index(op.f("ix_backup_url"), table_name="backup")
    op.drop_index(op.f("ix_backup_message_id"), table_name="backup")
    op.drop_index(op.f("ix_backup_id"), table_name="backup")
    op.drop_table("backup")
    op.drop_index(op.f("ix_admin_requirements_id"), table_name="admin_requirements")
    op.drop_table("admin_requirements")
    # ### end Alembic commands ###
